import React, { useState, useCallback, useEffect } from 'react';
import { Header } from './components/Header';
import { VoiceGallery } from './components/VoiceGallery';
import { TextInputSection } from './components/TextInputSection';
import { AudioPlayer } from './components/AudioPlayer';
import { Footer } from './components/Footer';
import { LoadingSpinner } from './components/LoadingSpinner';
import { VOICES } from './constants';
import type { Voice, Emotion, Accent, Language } from './types';
import { generateSpeech } from './services/geminiService';
import { createWavBlob } from './utils/audioUtils';

const App: React.FC = () => {
    const [selectedVoice, setSelectedVoice] = useState<Voice>(VOICES[0]);
    const [text, setText] = useState<string>('Hello, welcome to Imran TTS. Experience the most natural and human-like voices generated by artificial intelligence.');
    const [language, setLanguage] = useState<Language>({ code: 'en-US', name: 'English' });
    const [emotion, setEmotion] = useState<Emotion>('Calm');
    const [accent, setAccent] = useState<Accent>('American');
    const [generatedAudio, setGeneratedAudio] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);
    const [installPrompt, setInstallPrompt] = useState<any>(null);

    useEffect(() => {
        const handleBeforeInstallPrompt = (e: Event) => {
            e.preventDefault();
            setInstallPrompt(e);
        };

        window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt);

        return () => {
            window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
        };
    }, []);

    const handleInstallClick = () => {
        if (!installPrompt) {
            return;
        }
        installPrompt.prompt();
        installPrompt.userChoice.then((choiceResult: { outcome: 'accepted' | 'dismissed' }) => {
            if (choiceResult.outcome === 'accepted') {
                console.log('User accepted the install prompt');
            } else {
                console.log('User dismissed the install prompt');
            }
            setInstallPrompt(null);
        });
    };

    const handleGenerate = useCallback(async () => {
        if (!text.trim() || !selectedVoice) {
            setError('Please enter some text and select a voice.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedAudio(null);

        try {
            const audioBase64 = await generateSpeech(text, selectedVoice.geminiVoiceName, emotion, accent);
            setGeneratedAudio(audioBase64);
        } catch (err) {
            console.error('Error generating speech:', err);
            setError('Failed to generate speech. Please check your API key and try again.');
        } finally {
            setIsLoading(false);
        }
    }, [text, selectedVoice, emotion, accent]);
    
    const handleDownload = (format: 'mp3' | 'wav') => {
        if (!generatedAudio) return;
        
        const byteCharacters = atob(generatedAudio);
        const byteNumbers = new Array(byteCharacters.length);
        for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
        }
        const byteArray = new Uint8Array(byteNumbers);
        
        const blob = createWavBlob(byteArray);
        const url = URL.createObjectURL(blob);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = `imran-tts-speech.${format}`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };


    return (
        <div className="min-h-screen bg-gray-900 text-gray-200 font-sans flex flex-col">
            <Header installPrompt={installPrompt} onInstallClick={handleInstallClick} />
            <main className="flex-grow container mx-auto px-4 py-8">
                <VoiceGallery voices={VOICES} selectedVoice={selectedVoice} onSelectVoice={setSelectedVoice} />
                <TextInputSection 
                    text={text}
                    setText={setText}
                    language={language}
                    setLanguage={setLanguage}
                    emotion={emotion}
                    setEmotion={setEmotion}
                    accent={accent}
                    setAccent={setAccent}
                    onGenerate={handleGenerate}
                    isLoading={isLoading}
                />
                 {isLoading && (
                    <div className="flex justify-center items-center mt-8">
                        <LoadingSpinner />
                        <p className="ml-4 text-lg">Generating ultra-realistic voice...</p>
                    </div>
                )}
                {error && <p className="text-center text-red-400 mt-4">{error}</p>}
                {generatedAudio && !isLoading && (
                    <AudioPlayer audioBase64={generatedAudio} onDownload={handleDownload} />
                )}
            </main>
            <Footer />
        </div>
    );
};

export default App;